# Generated by Django 4.1.5 on 2023-01-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
