# Generated by Django 4.1.5 on 2023-02-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertimeline', '0007_comment_isreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='isreply',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
