# Generated by Django 4.1.5 on 2023-02-09 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertimeline', '0008_alter_comment_isreply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-post_created']},
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 9, 13, 20, 32, 891603, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
